### ISSUE TITLE
Can't connect to localhost

### ISSUE THREAD

**Issue by Free10** [Legedric/ptmagic#3]
Everything went fine until i tried to connect to the monitor. Command window running with no errors. Tried in Chrome and IE. Get the same error, "This page can't be displayed"

**Comment by yesmider** [comment]
see #2

**Comment by Free10** [comment]
my file does end with \\

**Comment by yesmider** [comment]
you connect to http://localhost:5000 ?

**Comment by Free10** [comment]
OK, so I have to wait for you to fix the port setting in the software before I can use it?

**Comment by Legedric** [comment]
> OK, so I have to wait for you to fix the port setting in the software before I can use it?

Unfortunately yes. I will work on a fix today and update this issue as soon as we released a fix for the port issue.

**Comment by Free10** [comment]
OK, Thanks

**Comment by Legedric** [comment]
The current re-upload includes a fix for this issue. Please check if you are now able to change the port in your settings.general.json file.

**Comment by Free10** [comment]
Still get nothing when I try to run IE. I also changed to a different port, didn't make any difference

**Comment by Legedric** [comment]
So you did re-download the current release and replaced all files in your "Monitor" folder with the one from the current ZIP?
Left the window open?

If so, please provide a screenshot of your command window and a screenshot of what you see in IE when trying to access it.

Thanks!

**Comment by XRIICrypto** [comment]
I've got it running now but the monitor says:
Monitor update failed!
PTMagic Monitor failed to update data. If this error does not go away by itself, please check the connection to your hosting

I've checked everything twice but can't seem to find why it's not working...

**Comment by Legedric** [comment]
@Free10 
Please be aware that the PTMagic bot may be running, but the monitor needs to be running as well.
So pülease make sure you see this window on your VPS AND leave this window open. Closing this will shutdown the monitor for PTMagic:
![image](https://user-images.githubusercontent.com/8308141/36342993-6ac03938-1406-11e8-8fd5-048c4475441c.png)

I am running everything on a VPS, too. Still you should be able to make a screenshot when you have your VPS open with Remote Desktop or other tools.

**Comment by Free10** [comment]
That is the same exact screen I have

**Comment by Legedric** [comment]
Then please provide a screenshot of your IE including the address bar.
