### ISSUE TITLE
Changing currency doesn't change the currency in topbar

### ISSUE THREAD

**Issue by JaySNL** [Legedric/ptmagic#306]
Changing the base currency from USD to, i.e EUR, doesn't change the $ icon in the top bar, see: https://prnt.sc/iqd0by

**Comment by smoochy** [comment]
I noticed the same. Have also set it to EUR, but using ETH instead of BTC. The value of 1 ETH is calculated correctly, but it still has the $ in front of it.

In addition, would it be possible to get more Europeanfriendly dates? Instead of 03/13/18, sth like 13.03.2018?

Cheers.

**Comment by Legedric** [comment]
@JaySNL Thanks, this will be changed with the next release.

@smoochy I will take a look at this.

**Comment by Legedric** [comment]
@smoochy All dates in PTM Monitor are shown depending on the language/culture of your machine. So if your machine is running with a European culture/language setting you will see European date formats.

The only area where the format is fixed is text box where you enter your transaction but you may use the calendar here so you do not have to work with the format.

**Comment by smoochy** [comment]
I checked the locale settings of my Ubuntu 16.04 VPS. You were right, it was set to en_US.

I generated a German one via `sudo locale-gen de_DE.UTF-8`. Afterwards I updated the /etc/default/locale file via `update-locale LANG=de_DE.UTF-8`. Rebooted the VPS afterwards.

Now `locale `prints out:

> LANG=de_DE.UTF-8
> LANGUAGE=
> LC_CTYPE="de_DE.UTF-8"
> LC_NUMERIC="de_DE.UTF-8"
> LC_TIME="de_DE.UTF-8"
> LC_COLLATE="de_DE.UTF-8"
> LC_MONETARY="de_DE.UTF-8"
> LC_MESSAGES="de_DE.UTF-8"
> LC_PAPER="de_DE.UTF-8"
> LC_NAME="de_DE.UTF-8"
> LC_ADDRESS="de_DE.UTF-8"
> LC_TELEPHONE="de_DE.UTF-8"
> LC_MEASUREMENT="de_DE.UTF-8"
> LC_IDENTIFICATION="de_DE.UTF-8"
> LC_ALL=

Because of the reboot PTM and PTMM also got restarted.
But the dates are still shown as mm/dd/yy.

Used this tutorial: https://askubuntu.com/questions/770309/cannot-permanently-change-locale-on-16-04-server

**Comment by Legedric** [comment]
No clue what may affect this on Unix systems. For me it is working on Windows.

**Comment by smoochy** [comment]
I used to have a Windows VPS, there I can remember the date being correctly shown according to my language settings.
Switched to Linux VPS and dates are now off.

I am not so used to Linux myself.imprecise thinking.

**Comment by smoochy** [comment]
For some reason, after following the tutorial again, and again rebooting, the dates are now being shown in European format.
